apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
  - image: vkfont/chatbot
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:{{.TAG}}'
deploy:
  helm:
    releases:
    - name: chatbot
      chartPath: makeomatic/bishop
      valuesFiles:
      - chart.yml
      namespace: default
      setValueTemplates:
        image.tag: '{{.TAG}}'
      wait: true
      recreatePods: true
      skipBuildDependencies: true
